---
- name: Start VMs
  hosts: localhost
  user: fullpower
  become: yes
  gather_facts: yes

  tasks:
    - name: Stop Vms
      command:
        cmd: virsh shutdown {{ item }}
      loop: "{{ groups['dockerSwarm'] }}"
      ignore_errors: True

    - name: Delete Vms
      command:
        cmd: virsh undefine {{ item }} --remove-all-storage
      loop: "{{ groups['dockerSwarm'] }}" 
      ignore_errors: True

    - name: Delete Disk
      command:
        cmd: rm /var/lib/libvirt/images/{{ item }}.qcow2
      loop: "{{ groups['dockerSwarm'] }}"
      ignore_errors: True

