- name: Deploys VM based on cloud image
  hosts: localhost
  user: fullpower
  gather_facts: yes
  become: yes

  tasks:
    - name: KVM Provision role
      include_role:
        name: kvm_provision
