---

#vm_net: default
vm_net: bridged-network #Modifico esta varible para que utilice un Bridge para comunicarnos directamente con la VM

vm_root_pass: "{{ vault_root_pass }}"
ssh_key: "{{ vault_publicKeys }}"

...