---

##Cloud image 
base_image_name: debian-12-generic-amd64-20240717-1811.qcow2
base_image_url: https://cloud.debian.org/images/cloud/bookworm/20240717-1811/{{ base_image_name }}
base_image_sha: 9ce1ce8c0f16958dd07bce6dd44d12f4d44d12593432a3a8f7c890c262ce78b0402642fa25c22941760b5a84d631cf81e2cb9dc39815be25bf3a2b56388504c6

#vm_net: default
vm_net: bridged-network #Modifico esta varible para que utilice un Bridge para comunicarnos directamente con la VM

vm_root_pass: "{{ vault_root_pass }}"
ssh_key: "{{ vault_publicKeys }}"


#Path to locate image
libvirt_pool_dir: "/var/lib/libvirt/images"

#VMs name
vm_name: docker_worker1

#Virtual CPUs
vm_vcpus: 2

#Ram Memory Definition
vm_ram_mb: 2048

#CleanUP
cleanup_tmp:

#Networking - (default - bridged-network)
vm_net: bridged-network

...